# Use the base image with Node.js
FROM node:10.22.1

ARG APPNAME
ARG APPENV
ENV APPNAME=$APPNAME
ENV APPENV=$APPENV

COPY . /$APPNAME
WORKDIR /$APPNAME

# Install dependencies
RUN npm install -g bower
RUN npm install -g grunt-cli
RUN npm install

# Build
RUN source config/tc-dev.sh
RUN grunt
RUN ls -lath

# Generate build.zip
RUN grunt deploy-compress

